#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"
stat="$(cat "$bat/status")"

icon() {
  if [ $stat == "Full" ]; then
    icon=""
  elif [ $stat == "Charging" ]; then
    if [ "$per" -gt "90" ]; then
        icon=""
      elif [ "$per" -gt "80" ]; then
        icon=""
      elif [ "$per" -gt "60" ]; then
        icon=""
      elif [ "$per" -gt "40" ]; then
        icon=""
      elif [ "$per" -gt "20" ]; then
        icon=""
      else
        icon=""
      fi
  elif [ "$per" -gt "90" ]; then
    icon=""
  elif [ "$per" -gt "80" ]; then
    icon=""
  elif [ "$per" -gt "70" ]; then
    icon=""
  elif [ "$per" -gt "60" ]; then
    icon=""
  elif [ "$per" -gt "50" ]; then
    icon=""
  elif [ "$per" -gt "40" ]; then
    icon=""
  elif [ "$per" -gt "30" ]; then
    icon=""
  elif [ "$per" -gt "20" ]; then
    icon=""
  elif [ "$per" -gt "10" ]; then
    icon=""
  elif [ "$per" -gt "0" ]; then
    icon=""
  else
    icon=""
  fi
  echo "$icon"
}

charge_cfg() {
  CACHE_FILE=~/.cache/eww-battery-chargemode.txt
  if [ $1 == "adaptive" ]; then
    pkexec /opt/dell/dcc/cctk --PrimaryBattChargeCfg=Adaptive
    result=$?
    echo "Result: >> "$result
  elif [ $1 == "full" ]; then
    pkexec /opt/dell/dcc/cctk --PrimaryBattChargeCfg=Express
    result=$?
    echo "Result: >> "$result
  elif [ $1 == "docked" ]; then
    pkexec /opt/dell/dcc/cctk --PrimaryBattChargeCfg=Custom:60-80
    result=$?
    echo "Result: >> "$result
  else
    mode=$(cat $CACHE_FILE 2>/dev/null)
    case $mode in
      "adaptive")
        echo "Adaptive"
        ;;
      "full")
        echo "Full"
        ;;
      "docked")
        echo "Docked"
        ;;
      *)
        echo "---"
        ;;
    esac
    exit
  fi

  if [[ $result == 0 ]]; then
    echo "Saving to cache..."
    echo $1 > $CACHE_FILE
  fi
}

case $1 in
  "icon")
    icon
    ;;
  "percent")
    echo $per
    ;;
  "status")
    echo $stat
    ;;
  "charge-mode")
    charge_cfg $2
    ;;
esac

