#!/bin/bash

dir=$(dirname $0)

case $1 in
  ascii-art)
    cat $dir/ascii-art.txt
    ;;
  info)
    echo "Distro    Arch Linux"
    echo "Kernel    $(uname -r)"
    echo "WM        qtile"
    echo "Uptime    $(uptime -p | awk '{print $2}')h $(uptime -p | awk '{print $4}')m"
    echo "Packages  $(pacman -Q | wc -l)"
    ;;
esac
