#!/bin/bash

EWW="/home/long/.local/bin/eww"

close_all() {
  ${EWW} close menu menu_closer
  ${EWW} close popup_closer
  ${EWW} close network
  ${EWW} close bluetooth
  ${EWW} close volume
  ${EWW} close battery
  ${EWW} close calendar

  rm -f "$HOME/.cache/eww-menu.lock"
  rm -f "$HOME/.cache/eww-network.lock"
  rm -f "$HOME/.cache/eww-bluetooth.lock"
  rm -f "$HOME/.cache/eww-volume.lock"
  rm -f "$HOME/.cache/eww-battery.lock"
  rm -f "$HOME/.cache/eww-calendar.lock"
}


menu() {
  LOCK_FILE="$HOME/.cache/eww-menu.lock"

  if [[ ! -f $LOCK_FILE ]]; then
    close_all
    ${EWW} open menu_closer
    ${EWW} open menu 
    touch $LOCK_FILE
  else
    ${EWW} close menu menu_closer
    rm $LOCK_FILE
  fi
}


network() {
  LOCK_FILE="$HOME/.cache/eww-network.lock"

  if [[ ! -f $LOCK_FILE && $1 != "close" ]]; then
    close_all
    ${EWW} open popup_closer
    ${EWW} open network
    touch $LOCK_FILE
  else
    ${EWW} close network popup_closer
    rm $LOCK_FILE
  fi
}

bluetooth() {
  LOCK_FILE="$HOME/.cache/eww-bluetooth.lock"

  if [[ ! -f $LOCK_FILE ]]; then
    close_all
    ${EWW} open popup_closer
    ${EWW} open bluetooth
    touch $LOCK_FILE
  else
    ${EWW} close bluetooth popup_closer
    rm $LOCK_FILE
  fi
}

volume() {
  LOCK_FILE="$HOME/.cache/eww-volume.lock"

  if [[ ! -f $LOCK_FILE ]]; then
    close_all
    ${EWW} open popup_closer
    ${EWW} open volume
    touch $LOCK_FILE
  else
    ${EWW} close volume popup_closer
    rm $LOCK_FILE
  fi
}

battery() {
  LOCK_FILE="$HOME/.cache/eww-battery.lock"

  if [[ ! -f $LOCK_FILE ]]; then
    close_all
    ${EWW} open popup_closer
    ${EWW} open battery
    touch $LOCK_FILE
  else
    ${EWW} close battery popup_closer
    rm $LOCK_FILE
  fi
}

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"

  if [[ ! -f $LOCK_FILE ]]; then
    close_all
    ${EWW} open popup_closer
    ${EWW} open calendar
    touch $LOCK_FILE
  else
    ${EWW} close calendar popup_closer
    rm $LOCK_FILE
  fi
}

case $1 in
  "calendar")
    calendar
    ;;
  "network")
    network
    ;;
  "bluetooth")
    bluetooth
    ;;
  "volume")
    volume
    ;;
  "battery")
    battery
    ;;
  "menu")
    menu
    ;;
  "close-all")
    close_all
    ;;
esac
