#!/bin/bash
cd `dirname $0`

./pop menu
case $1 in
  "Suspend")
    systemctl suspend
  ;;
  "Hibernate")
    systemctl hibernate
  ;;
  "Lock")
  ;;
  "Shutdown")
    shutdown now
  ;;
  "Restart")
    reboot
  ;;
  "Logout")
    ./qtile shutdown
  ;;
esac
