#!/bin/bash

options=""
options="${options}Sleep\n"
options="${options}Lock\n"
options="${options}Logout\n"
options="${options}Shutdown\n"
options="${options}Restart\n"
options="${options}Hibernate\n"
options="${options}ScreenOff"

if [ -z $1 ]; then
choice=$(echo -e $options | \
    rofi -dmenu -p "Power" -no-custom -filter "" \
    -theme $HOME/.config/rofi/power-menu/power.rasi)
else
    choice=$1
fi

echo "Choice: $choice"

case $choice in
    "Sleep")
        systemctl suspend
        swaylock
        ~/.local/bin/reload-widgets
    ;;
    "Hibernate")
        systemctl hibernate
    ;;
    "ScreenOff")
        sleep 1
        niri msg action power-off-monitors
    ;;
    "Lock")
        swaylock
    ;;
    "Logout")
        niri msg action quit
    ;;
    "Shutdown")
        shutdown now
    ;;
    "Restart")
        reboot
    ;;
    *)
        echo "Invalid Choice"
    ;;
esac
